version: 2.1
orbs:
  docker: circleci/docker@2.2.0
jobs:
  build:
    executor: docker/machine
    steps:
      - checkout
      - docker/dockerlint:
          dockerfile: Dockerfile
          treat-warnings-as-errors: true
      - run:
          command: chmod +x build_push_image_karsajobs.sh && ./build_push_image_karsajobs.sh
workflows:
  lint-and-build-dockerfile:
    jobs:
      - build
